# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 695)
        MainWindow.setStyleSheet(
            "QHBoxLayout QLabel {\n"
            "margin: 10px;\n"
            "border-radius: 4px;\n"
            "background-color: lightgray;\n"
            "}"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_loadVideo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_loadVideo.setEnabled(True)
        self.btn_loadVideo.setObjectName("btn_loadVideo")
        self.horizontalLayout.addWidget(self.btn_loadVideo)
        self.label_video_url = QtWidgets.QLabel(self.centralwidget)
        self.label_video_url.setObjectName("label_video_url")
        self.horizontalLayout.addWidget(self.label_video_url)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.btn_play_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play_pause.setEnabled(False)
        self.btn_play_pause.setObjectName("btn_play_pause")
        self.horizontalLayout.addWidget(self.btn_play_pause)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("border: 1px solid grey;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn_addStation = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addStation.setEnabled(False)
        self.btn_addStation.setMinimumSize(QtCore.QSize(28, 28))
        self.btn_addStation.setMaximumSize(QtCore.QSize(28, 28))
        self.btn_addStation.setObjectName("btn_addStation")
        self.horizontalLayout_3.addWidget(self.btn_addStation)
        self.btn_removeStation = QtWidgets.QPushButton(self.centralwidget)
        self.btn_removeStation.setEnabled(False)
        self.btn_removeStation.setMinimumSize(QtCore.QSize(28, 28))
        self.btn_removeStation.setMaximumSize(QtCore.QSize(28, 28))
        self.btn_removeStation.setObjectName("btn_removeStation")
        self.horizontalLayout_3.addWidget(self.btn_removeStation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cb_showDetections = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_showDetections.setChecked(True)
        self.cb_showDetections.setObjectName("cb_showDetections")
        self.horizontalLayout_4.addWidget(self.cb_showDetections)
        self.cb_showStations = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_showStations.setChecked(True)
        self.cb_showStations.setObjectName("cb_showStations")
        self.horizontalLayout_4.addWidget(self.cb_showStations)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_loadVideo.setText(_translate("MainWindow", "Load Video"))
        self.label_video_url.setText(_translate("MainWindow", "No video Selected"))
        self.btn_play_pause.setText(_translate("MainWindow", "Play"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Work"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sleep"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Empty"))
        self.btn_addStation.setText(_translate("MainWindow", "+"))
        self.btn_removeStation.setText(_translate("MainWindow", "-"))
        self.cb_showDetections.setText(_translate("MainWindow", "Show Detections"))
        self.cb_showStations.setText(_translate("MainWindow", "Show Stations"))
